msm8996-common:Fix bulf errors
error: Cannot add manifest fragment
/vendor/etc/vintf/manifest/vendor.qti.gnss@3.0-service.xml: HAL vendor.qti.gn
ss has a conflict: Conflicting FqInstance: @1.0::ILocHidlGnss/gnss_vendor (from
 /vendor/etc/vintf/manifest.xml) vs. @1.2::ILocHidlGnss/gnss_vendor (from /vendo
r/etc/vintf/manifest/vendor.qti.gnss@3.0-service.xml). Check whether or not mult
iple modules providing the same HAL are installed.

error: Cannot add manifest fragmen
t /vendor/etc/vintf/manifest/vendor.qti.gnss@3.0-service.xml: HAL android.hardw
are.gnss has a conflict: Conflicting FqInstance: @1.0::IGnss/gnss_vendor (from
/vendor/etc/vintf/manifest.xml) vs. @1.0::IGnss/gnss_vendor (from /vendor/etc/vi
ntf/manifest/vendor.qti.gnss@3.0-service.xml). Check whether or not multiple mod
ules providing the same HAL are installed.