msm8996-common:Fix build error
releasetools.py, line 59, in AddModemAssertion
m = re.search(r require\s+version-modem\s =\s (.+), android_info.decode( utf-8))
AttributeError: str object has no attribute decode. Did you mean: encode?
08:38:39 ninja failed with: exit status 1